# Cloudflare Pages configuration

name = "houseboard"
compatibility_date = "2026-01-01"
pages_build_output_dir = "dist"

[vars]
JWT_SECRET = "dev-secret-do-not-use-in-production"

# [[kv_namespaces]]
# binding = "KV"
# id = ""
# preview_id = ""

# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = ""
# preview_bucket_name = ""

[[d1_databases]]
binding = "DB"
database_name = "houseboard-db"
database_id = "357ad9cf-6d66-4a9c-9fb5-2bbac9e7f2c5"
